html_template = (
    '<html><body>'
    '<p>New Switch games on sale today ({qty})</p>'
    '<div class="wrapper">{cards}</div>'
    '</body>'
    '<style>'
    '* {{margin: 0;}}'
    'body {{background: #fff;}}'
    'a {{color: black;font-weight: 600;text-overflow: ellipsis}}'
    'th, td {{font-weight: 300;}}'
    'p {{padding: 0.5em;background-color: #eee;text-align: center;'
    'border-radius:0.5rem;box-shadow: 0 0 0.5rem -0.25rem black;}}'
    '.wrapper {{columns: 15em;padding: 1em;}}'
    '.card {{background: #eee;break-inside: avoid;margin-bottom: 0.5em;'
    'box-shadow: 0 0 0.5rem -0.25rem black;border-radius: 0.5rem;}}'
    'img, table {{width: 100%;text-align: center;'
    'border-radius: 0.5rem 0.5rem 0 0;}}'
    '</style>'
    '</html>'
)

card_template = (
    '<div class="card">'
    '<a href="{url}"><img alt="{title}" src="{img}"></a>'
    '<table>'
    '<thead>'
    '<tr>{headers}</tr>'
    '</thead>'
    '<tbody><tr>{values}</tr></tbody>'
    '</table></div>'
)
