style = (
    '* {{'
    '    margin: 0;'
    '}}'
    'p {{'
    '    padding: 0.5rem;'
    '    background-color: #eee;'
    '    text-align: center;'
    '    border-radius: 0.5rem;'
    '    box-shadow: 0 0 0.5rem -0.25rem black;'
    '}}'
    '.wrapper {{'
    '    columns: 15rem;'
    '    padding: 1rem;'
    '    font-family: sans-serif;'
    '}}'
    '.card {{'
    '    background: #eee;'
    '    break-inside: avoid;'
    '    margin-bottom: 0.5em;'
    '    box-shadow: 0 0 0.5rem -0.25rem black;'
    '    border-radius: 0.5rem;'
    '    overflow: hidden;'
    '    position: relative;'
    '}}'
    '.discount {{'
    '    position: absolute;'
    '    top: 0;'
    '    right: 0;'
    '    width: 6rem;'
    '    height: 6rem;'
    '    background: rgb(170, 45, 45);'
    '    transform-origin: bottom right;'
    '    transform: translateY(-1.75rem) rotate(45deg);'
    '}}'
    '.discount > span {{'
    '    color: #fff;'
    '    font-weight: bolder;'
    '    text-align: center;'
    '    position: absolute;'
    '    bottom: 0.4rem;'
    '    width: 100%;'
    '}}'
    '.prices {{'
    '    display: flex;'
    '    flex-direction: row;'
    '    justify-content: space-evenly;'
    '    width: 100%;'
    '}}'
    '.store {{'
    '    display: flex;'
    '    flex-direction: column;'
    '    text-align: center;'
    '}}'
    '.title {{'
    '    font-weight: bold;'
    '}}'
    'img {{'
    '    width: 100%;'
    '}}'
)

html_template = (
    '<p>New Switch games on sale today ({qty})</p>'
    '<div class="wrapper">{cards}</div>'
    f'<style>{style}</style>'
)

card_template = (
    '<div class="card">'
    '    <a href="{url}"><img alt="{title}" src="{img}"></a>'
    '    <div class="discount"><span>{discount}%</span></div>'
    '    <div class="prices">'
    '        {content}'
    '    </div>'
    '</div>'
)

content_template = (
    '<div class="store">'
    '    <span class="title">{store}</span>'
    '    <span>{unit} {price}</span>'
    '</div>'
)
